package better.anticheat.core.player.tracker.impl.confirmation.cookie;

/**
 * Interface for dynamic cookie ID allocation algorithms.
 * Implementations can provide different strategies for generating byte sequences
 * used in cookie packets for confirmation tracking.
 */
public interface CookieIdAllocator {
    
    /**
     * Allocates the next cookie ID as a byte array.
     * 
     * @return a byte array representing the next cookie ID
     */
    byte[] allocateNext();
    
    /**
     * Checks if the given byte array represents a valid cookie ID
     * that could have been generated by this allocator.
     * 
     * @param cookieId the byte array to validate
     * @return true if this is a valid cookie ID from this allocator
     */
    boolean isValidCookieId(byte[] cookieId);
    
    /**
     * Gets the expected length of cookie IDs generated by this allocator.
     * 
     * @return the byte length of cookie IDs
     */
    int getCookieIdLength();
}
